import test from 'node:test';
import assert from 'node:assert/strict';
import {frontendModules} from './helpers/frontend-module.mjs';
const {load}=frontendModules();
const {buildBotPositionView}=load('features/bots/position-view.ts');
const now=Date.parse('2026-09-10T20:00:00Z');
function snapshot(){return {runtime_status:{bot_name:'ok_rsi',updated_at:new Date(now-1000).toISOString(),active_orders_count:2,controllers:[{controller_id:'eth',pair:'ETH-USDC',price_quote:110,custom_info:{episode:{enabled:true,phase:'DISTRIBUTE',base:'10',cost:'1000',cost_known:true,target_base:'6',minimum_profit_price:'102',exit_risk_clear:true,reason:'trail_wait'},trailing_policy:{policy:'episode_aggregate',peak:'115',floor:'108',target_base:'6'}}}],positions_held:[{controller_id:'eth',pair:'ETH-USDC',amount_base:3,breakeven_price:100,unrealized_pnl_quote:30}],active_executors:[]},monitoring:{bot_name:'ok_rsi',stale_threshold_seconds:30}};}
test('uses tracked episode bag once, mark value and gross PnL; separates conditional reduction from active orders',()=>{const view=buildBotPositionView(snapshot(),'ok_rsi',now);assert.equal(view.activeOrderCount,2);const row=view.pairs[0];assert.equal(row.base,10);assert.equal(row.markValue,1100);assert.equal(row.bagPnl,100);assert.equal(row.breakeven,100);assert.equal(row.plannedReduction,4);assert.equal(row.floor,108);assert.equal(row.profitPrice,102);assert.equal(view.orders,null);});
test('unknown cost hides basis/PnL and unarmed acquisition does not imply a full next sell',()=>{const p=snapshot();Object.assign(p.runtime_status.controllers[0].custom_info.episode,{cost_known:false,phase:'ACCUMULATE',target_base:'0'});const row=buildBotPositionView(p,'ok_rsi',now).pairs[0];assert.equal(row.breakeven,null);assert.equal(row.bagPnl,null);assert.equal(row.plannedReduction,null);});
test('stale, missing timestamp, wrong bot and malformed numbers fail closed',()=>{for(const change of [{updated_at:new Date(now-31000).toISOString()},{updated_at:null},{bot_name:'other'}]){const p=snapshot();Object.assign(p.runtime_status,change);assert.throws(()=>buildBotPositionView(p,'ok_rsi',now));}const p=snapshot();p.runtime_status.controllers[0].price_quote='NaN';assert.equal(buildBotPositionView(p,'ok_rsi',now).pairs[0].markValue,null);});
test('legacy position value_quote is basis value: mark holding value comes from current price',()=>{const p=snapshot();p.runtime_status.controllers[0].custom_info={};p.runtime_status.positions_held[0].value_quote=300;const row=buildBotPositionView(p,'ok_rsi',now).pairs[0];assert.equal(row.base,3);assert.equal(row.markValue,330);assert.equal(row.bagPnl,30);assert.equal(row.inventorySource,'Retained positions');assert.equal(row.plannedReduction,null);});
test('different controller holdings never leak through a shared pair',()=>{const p=snapshot();p.runtime_status.controllers.push({controller_id:'other',pair:'ETH-USDC',price_quote:110});const row=buildBotPositionView(p,'ok_rsi',now).pairs[1];assert.equal(row.base,0);assert.equal(row.bagPnl,null);});

test('real position panel renders levels, scope and drilldowns; stale observations suppress all old prices',async()=>{
 const React=await import('react');const {renderToStaticMarkup}=await import('react-dom/server');
 const {load}=frontendModules({'react-router-dom':{Link:({to,children,...rest})=>React.createElement('a',{href:to,...rest},children)}});
 const {BotPositionObservation}=load('components/bots/NativeBotPositions.tsx');
 const html=renderToStaticMarkup(React.createElement(BotPositionObservation,{payload:snapshot(),bot:'ok_rsi',now}));
 for(const text of ['Active limit orders','Bag holding','Bag market value','Bag unrealized PnL','Next sell and trailing exit','Observed price levels','Planned bag reduction','before exit costs','record=fills'])assert.ok(html.includes(text),text);
 assert.doesNotMatch(html,/No active orders/);
 const stale=renderToStaticMarkup(React.createElement(BotPositionObservation,{payload:snapshot(),bot:'ok_rsi',now:now+31000}));
 assert.match(stale,/stale/);assert.doesNotMatch(stale,/1,100|ETH-USDC|Bag holding/);
});

test('legacy shared-pair controllers do not turn unattributed holdings into zero bags',()=>{const p=snapshot();p.runtime_status.controllers=[{pair:'ETH-USDC',price_quote:110},{pair:'ETH-USDC',price_quote:110}];const result=buildBotPositionView(p,'ok_rsi',now);for(const row of result.pairs){assert.equal(row.base,null);assert.equal(row.markValue,null);assert.equal(row.bagPnl,null);}});

test('explicit failed enriched observation withholds bag values even with empty retained positions',()=>{const p=snapshot();p.runtime_status.controllers[0].observation_status='unavailable';p.runtime_status.controllers[0].custom_info={};p.runtime_status.positions_held=[];const row=buildBotPositionView(p,'ok_rsi',now).pairs[0];assert.equal(row.base,null);assert.equal(row.markValue,null);assert.equal(row.bagPnl,null);assert.match(row.inventorySource,/unavailable/);});

test('duplicate controller identities cannot duplicate a bag',()=>{const p=snapshot();p.runtime_status.controllers.push(p.runtime_status.controllers[0]);assert.throws(()=>buildBotPositionView(p,'ok_rsi',now),/duplicated/);});

test('actual owner snapshot fixture flows through the UI projection without changing quantities', {skip: !process.env.BOT_OBSERVATION_FIXTURE}, async()=>{const fs=await import('node:fs');const runtime=JSON.parse(fs.readFileSync(process.env.BOT_OBSERVATION_FIXTURE,'utf8'));const view=buildBotPositionView({runtime_status:runtime,monitoring:{bot_name:runtime.bot_name,stale_threshold_seconds:30}},runtime.bot_name,Date.parse(runtime.updated_at)+1000);assert.equal(view.activeOrderCount,1);assert.equal(view.pairs[0].base,10);assert.equal(view.pairs[0].markValue,125);assert.equal(view.pairs[0].bagPnl,35);assert.equal(view.pairs[0].pendingSells[0].remaining_amount_base,'2');assert.equal(view.pairs[0].executors[0].trailing_trigger_price,'12');assert.equal(view.orders[0].remaining_amount_base,'2');assert.equal(view.ordersStatus.complete,true);});

test('complete connector order list supplies total count; legacy count is explicitly limit-only',()=>{const p=snapshot();assert.equal(buildBotPositionView(p,'ok_rsi',now).orderCountLabel,'Active limit orders');p.runtime_status.active_orders=[{order_id:'o1',pair:'ETH-USDC'},{order_id:'o2',pair:'ETH-USDC'},{order_id:'o3',pair:'ETH-USDC'}];p.runtime_status.active_orders_status={complete:true};const view=buildBotPositionView(p,'ok_rsi',now);assert.equal(view.activeOrderCount,3);assert.equal(view.orderCountLabel,'Active orders');});

test('cancellation-pending and expired sell requests never look like pending fresh orders',()=>{const p=snapshot();p.runtime_status.controllers[0].custom_info.pending_sell_requests=[{request_id:'canceled',termination_requested:true,expires_at:now/1000+100},{request_id:'expired',termination_requested:false,expires_at:now/1000-1},{request_id:'pending',termination_requested:false,expires_at:now/1000+100}];const rows=buildBotPositionView(p,'ok_rsi',now).pairs[0].pendingSells;assert.deepEqual(rows.map(row=>row.request_state),['Cancellation requested','Expiry reached; awaiting owner','Pending owner request']);});
