import test from 'node:test';
import assert from 'node:assert/strict';
import {clearPendingEntryCommand,entryPath,entryObservation,entryCommandObserved,entryPendingStorageKey,entryPublicationMessage,readPendingEntryCommand,writePendingEntryCommand} from '../src/lib/native-entry-controls.ts';
const now=1900000000000;
const payload=()=>({status:'success',verified_at:now/1000,command_allowed:true,data:{bot_name:'v2',bot_status:'running',controllers:[{controller_id:'a',entry_paused:true,last_command_id:'x',updated_at:now/1000}]}});
class MemoryStorage{constructor(){this.data=new Map();}getItem(key){return this.data.has(key)?this.data.get(key):null;}setItem(key,value){this.data.set(key,value);}removeItem(key){this.data.delete(key);}}
test('entry routes encode exact scope and reject arbitrary operations',()=>{assert.equal(entryPath('a/b','v2','pause'),'/api/v1/servers/a%2Fb/bots/v2/native/entries/pause');assert.throws(()=>entryPath('a','b','start'));});
test('entry observations require current bound complete state',()=>{assert.equal(entryObservation(payload(),'v2',now,now).allowed,true);assert.equal(entryObservation(payload(),'other',now,now).allowed,false);assert.equal(entryObservation(payload(),'v2',now,now-15000).allowed,false);const p=payload();p.data.controllers=[];assert.equal(entryObservation(p,'v2',now,now).allowed,false);});
test('entry freshness uses browser receipt age rather than comparing browser and server clocks',()=>{for(const skew of [-120000,120000]){const p=payload();p.verified_at=(now+skew)/1000;assert.equal(entryObservation(p,'v2',now,now).allowed,true);}});
test('publication never grants execution and requires matching observed command state',()=>{assert.equal(entryPublicationMessage(202,{execution_verified:true}).rejected,false);assert.match(entryPublicationMessage(202,{}).text,/does not confirm/);assert.equal(entryPublicationMessage(409,{detail:'Same day'}).rejected,true);const cmd={id:'x',action:'pause'};assert.equal(entryCommandObserved(payload(),'v2',now,now,cmd),true);assert.equal(entryCommandObserved(payload(),'v2',now,now,{...cmd,id:'other'}),false);assert.equal(entryCommandObserved(payload(),'v2',now,now,{...cmd,action:'resume'}),false);});
test('matching native command is not rejected by browser/server clock skew',()=>{const cmd={id:'x',action:'pause'};const skewed=payload();skewed.data.controllers[0].updated_at=(now-120000)/1000;assert.equal(entryCommandObserved(skewed,'v2',now,now,cmd),true);const invalid=payload();invalid.data.controllers[0].updated_at=Number.NaN;assert.equal(entryCommandObserved(invalid,'v2',now,now,cmd),false);});
test('pending native command survives an in-tab reload boundary with exact identity scope',()=>{const storage=new MemoryStorage();const key=entryPendingStorageKey('srv/a','v2',7);const command={id:'cmd_123-abc',action:'pause'};assert.equal(writePendingEntryCommand(storage,key,command),true);assert.deepEqual(readPendingEntryCommand(storage,key),{status:'valid',command});assert.equal(readPendingEntryCommand(storage,entryPendingStorageKey('srv/a','other',7)).status,'empty');assert.equal(readPendingEntryCommand(storage,entryPendingStorageKey('srv/a','v2',8)).status,'empty');assert.equal(clearPendingEntryCommand(storage,key),true);assert.equal(readPendingEntryCommand(storage,key).status,'empty');});
test('pending command storage rejects malformed or unverifiable receipts and fails closed when unavailable',()=>{const storage=new MemoryStorage();const key=entryPendingStorageKey('srv','v2',7);storage.setItem(key,'{"id":"cmd","action":"pause","extra":true}');assert.equal(readPendingEntryCommand(storage,key).status,'invalid');storage.setItem(key,'not-json');assert.equal(readPendingEntryCommand(storage,key).status,'invalid');storage.setItem(key,'{"id":"bad id","action":"pause"}');assert.equal(readPendingEntryCommand(storage,key).status,'invalid');storage.setItem(key,'{"id":"cmd","action":"start"}');assert.equal(readPendingEntryCommand(storage,key).status,'invalid');assert.deepEqual(readPendingEntryCommand(null,key),{status:'unavailable',command:null});assert.equal(writePendingEntryCommand(null,key,{id:'cmd',action:'pause'}),false);assert.throws(()=>entryPendingStorageKey('srv','v2',0));});
test('gateway failures retain the pending command because publication may have reached the owner',()=>{
  assert.equal(entryPublicationMessage(502,{detail:'Bad gateway'}).rejected,false);
  assert.equal(entryPublicationMessage(503,{detail:'Unavailable'}).rejected,false);
  assert.match(entryPublicationMessage(502,{}).text,/outcome unknown/);
});
