from __future__ import annotations

import os

from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from pydantic import BaseModel

from condor.web.auth import create_jwt, get_current_user, redeem_login_token
from condor.web.models import LoginResponse, WebUser
from config_manager import UserRole, get_config_manager

router = APIRouter(tags=["auth"])


@router.post('/auth/tailscale', response_model=LoginResponse)
async def tailscale_login(request: Request, response: Response):
    """Opt-in owner login behind localhost-bound Tailscale Serve only.

    Serve strips caller-supplied identity headers. The web-only launcher binds
    loopback and disables proxy-header rewriting of the socket peer address.
    Other local processes are inside this machine's existing trust boundary.
    """
    login = os.environ.get('CONDOR_TAILSCALE_LOGIN', '')
    user_id = os.environ.get('CONDOR_TAILSCALE_USER_ID', '')
    if not login or not user_id.isdigit():
        raise HTTPException(404, 'Tailscale sign-in is not configured')
    if (request.client is None or request.client.host not in {'127.0.0.1', '::1'}
            or request.headers.get('Tailscale-User-Login') != login):
        raise HTTPException(403, 'Open Condor through your private Tailscale link')
    role = get_config_manager().get_user_role(int(user_id))
    if role not in (UserRole.USER, UserRole.ADMIN):
        raise HTTPException(403, 'Access denied')
    response.headers['Cache-Control'] = 'no-store'
    response.headers['Referrer-Policy'] = 'no-referrer'
    return LoginResponse(
        token=create_jwt(int(user_id), first_name='Operator', role=role.value),
        user=WebUser(id=int(user_id), first_name='Operator', role=role.value),
    )


class TokenLoginRequest(BaseModel):
    token: str


@router.post("/auth/token-login", response_model=LoginResponse)
async def token_login(req: TokenLoginRequest, response: Response):
    """Login using a one-time token generated by the /web Telegram command."""
    # Defense in depth: never leak the one-time login token (or the issued JWT)
    # to third parties via the Referer header, and keep the response uncached.
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["Cache-Control"] = "no-store"

    info = redeem_login_token(req.token)
    if info is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired login token",
        )

    user_id = info["user_id"]
    cm = get_config_manager()
    role = cm.get_user_role(user_id)

    if role not in (UserRole.USER, UserRole.ADMIN):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied. Ask the admin to approve your account in Telegram.",
        )

    jwt_token = create_jwt(
        user_id=user_id,
        username=info.get("username", ""),
        first_name=info.get("first_name", ""),
        role=role.value,
    )

    user = WebUser(
        id=user_id,
        username=info.get("username", ""),
        first_name=info.get("first_name", ""),
        role=role.value,
    )
    return LoginResponse(token=jwt_token, user=user)


@router.get("/auth/me", response_model=WebUser)
async def me(user: WebUser = Depends(get_current_user)):
    return user


# ── User preferences ──


@router.get("/auth/preferences")
async def get_preferences(user: WebUser = Depends(get_current_user)):
    """Get all preferences for the current user."""
    cm = get_config_manager()
    return cm.get_user_preferences(user.id)


class PreferencesUpdate(BaseModel):
    updates: dict


@router.patch("/auth/preferences")
async def update_preferences(
    body: PreferencesUpdate,
    user: WebUser = Depends(get_current_user),
):
    """Merge preference updates for the current user."""
    cm = get_config_manager()
    cm.set_user_preferences(user.id, body.updates)
    return cm.get_user_preferences(user.id)
